ci: temporarily disable uploading test results to Codecov:
There is an unknown error when generating test report output file:

```bash
ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

We may have to switch to another test-result reporting service.